### ISSUE TITLE
Regarding Updates - If you would add more tiles and blocks, This would be even much better and propably more people would use this. Anyways, I think it's pretty hard to program.

### ISSUE THREAD

**Issue by TeenMike** [Nenkai/PixelPlanner#2]

**Comment by Nenkai** [comment]
There is an updated version that you can find [here](https://github.com/ColdUnwanted/PWPlanner), PS I would've prefered if the owner of that repository forked rather than make a new repo.

Having no interest into the game I do not have more time to spend on this project. If anyone wants to bother pull requests are open.
